name: Generate Branch Info

on:
  push

permissions:
  contents: write  
  
jobs:
  generate-branch-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all branches
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Fetch all branches
        run: |
          # Fetch all remote branches and create local tracking branches
          git fetch origin
          for branch in $(git ls-remote --heads origin | awk '{print $2}' | sed 's|refs/heads/||'); do
            if [ "$branch" != "main" ]; then
              git fetch origin $branch:$branch
            fi
          done

          echo "✅ Local branches after fetch:"
          git branch

      - name: Generate branch-info.txt
        run: |
          echo "Branches in this repo:" > branch-info.txt
          for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/); do
            sha=$(git rev-parse "$branch")
            echo "- $branch ($sha)" >> branch-info.txt
          done
          echo "✅ Contents of branch-info.txt:"
          cat branch-info.txt

      - name: Commit and push branch-info.txt to main branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add branch-info.txt
          git commit -m "Auto-update branch-info.txt" || echo "No changes to commit"
          git push origin main
